dist: trusty
sudo: true
cache: pip
language: python
python: '3.6' # From specification given

install:
  pip install -r requirements_test.txt

before_script:
  - python3 manage.py makemigrations
  - python3 manage.py migrate

script:
  - python manage.py test
